name: stripe_sdk
description: A simple and flexible Stripe library for Flutter. Has complete support for SCA/PSD2, and is implemented as a native dart library.
version: 2.1.1
author: Lars-Kristian Dahl <lars.dahl@gmail.com>
homepage: https://github.com/ezet/stripe_sdk

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0 
  url_launcher: ^5.1.2
  uni_links: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

